/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FootprintChartsRouteImport } from './routes/footprint-charts'
import { Route as IndexRouteImport } from './routes/index'

const FootprintChartsRoute = FootprintChartsRouteImport.update({
  id: '/footprint-charts',
  path: '/footprint-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/footprint-charts': typeof FootprintChartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/footprint-charts': typeof FootprintChartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/footprint-charts': typeof FootprintChartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/footprint-charts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/footprint-charts'
  id: '__root__' | '/' | '/footprint-charts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FootprintChartsRoute: typeof FootprintChartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/footprint-charts': {
      id: '/footprint-charts'
      path: '/footprint-charts'
      fullPath: '/footprint-charts'
      preLoaderRoute: typeof FootprintChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FootprintChartsRoute: FootprintChartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
